import type { NextPage } from 'next'
import Head from 'next/head'
import { Filter, Header, Main } from '../src/components'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Wine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header />
      <Main>
        <Filter />
      </Main>
    </div>
  )
}

export default Home
